# Generated by Django 4.0.4 on 2022-05-31 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_apellido_alter_persona_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='familia.persona')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.IntegerField(max_length=100)),
            ],
            bases=('familia.persona',),
        ),
    ]
