# Generated by Django 4.0.4 on 2022-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_alter_vehiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.IntegerField(),
        ),
    ]
