# Generated by Django 4.0.4 on 2022-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0007_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='altura',
            field=models.FloatField(default=0.0),
        ),
    ]
